# Useful when only the shell executor is available
# Java must be installed in the runner

stages:
  - deps_check

owasp_dependency_check:
  stage: deps_check
  script:
    - java -version
    - wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
    - unzip dependency-check-6.5.1-release.zip
    - dependency-check/bin/dependency-check.sh --scan . --format ALL --project $CI_PROJECT_NAME --failOnCVSS 0
    - if [ $(grep -c "vulnerabilities" dependency-check-report.json) -gt 0 ]; then exit 1; fi
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"
  tags:
    - java
